M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date Tue May  3 12:56:29 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-03T12:56:29+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X85.22Y43.53
X85.22Y37.75
T2
X38.928Y-9.77
X51.588Y-23.67
T0
M30
